# Generated by Django 5.1.4 on 2026-07-29 02:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workspace_widget_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(max_length=253, unique=True)),
                ('verify_token', models.CharField(editable=False, max_length=48)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='accounts.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['hostname'], name='accounts_do_hostnam_26be58_idx')],
            },
        ),
    ]
