# Generated by Django 5.1.4 on 2026-07-28 03:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_workspace_membership_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('current_page', models.CharField(blank=True, max_length=1024)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('chat', 'Chat'), ('email', 'Email')], default='chat', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('snoozed', 'Snoozed'), ('resolved', 'Resolved')], default='open', max_length=8)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('agent_last_read_seq', models.PositiveIntegerField(default=0)),
                ('contact_last_read_seq', models.PositiveIntegerField(default=0)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('summary_upto_seq', models.PositiveIntegerField(default=0)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='inbox.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seq', models.PositiveIntegerField()),
                ('sender_type', models.CharField(choices=[('contact', 'Contact'), ('agent', 'Agent'), ('system', 'System')], max_length=8)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('client_msg_id', models.UUIDField(default=uuid.uuid4)),
                ('email_message_id', models.CharField(blank=True, max_length=998)),
                ('email_in_reply_to', models.CharField(blank=True, max_length=998)),
                ('delivery_state', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=8)),
                ('raw_mime', models.TextField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inbox.conversation')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'email'], name='inbox_conta_workspa_fcc06d_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('workspace', 'email'), name='uniq_contact_workspace_email'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['workspace', 'status', '-last_message_at'], name='inbox_conve_workspa_5cc2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['workspace', 'assignee', '-last_message_at'], name='inbox_conve_workspa_20d802_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'seq'], name='inbox_messa_convers_4e4ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['email_message_id'], name='inbox_messa_email_m_f2a423_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'seq'), name='uniq_message_conv_seq'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'client_msg_id'), name='uniq_message_conv_client_id'),
        ),
    ]
