# Generated by Django 5.1.4 on 2026-07-28 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workspace_widget_config'),
        ('inbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['workspace', 'channel', '-last_message_at'], name='inbox_conve_workspa_73f40b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', 'snoozed_until'], name='idx_conv_snooze_expiry'),
        ),
    ]
