# Generated by Django 5.1.4 on 2026-07-28 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_conversation_phase5_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='summary_degraded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SummaryJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('degraded', 'Degraded'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('upto_seq', models.PositiveIntegerField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_jobs', to='inbox.conversation')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='inbox_summa_status_9af83d_idx'), models.Index(fields=['conversation', '-created_at'], name='inbox_summa_convers_9269f7_idx')],
            },
        ),
    ]
